supergraph:
  listen: 0.0.0.0:4000
  introspection: true
cors:
  allow_credentials: true
  origins:
    - https://studio.apollographql.com
    - https://api-dev.knighthacks.org
    - http://localhost:3000
    - http://localhost:4000
  match_origins:
    - "^(http|https)://localhost"
headers:
  all:
    request:
      - propagate:
          named: 'authorization'
rhai:
  main: "script.rhai"
  scripts: "/etc/config/"
sandbox:
  enabled: true
homepage:
  enabled: false
include_subgraph_errors:
  all: true # Propagate errors from all subraphs
